services:
  - type: web
    name: webag-professional
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: webag-db
          property: connectionString
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PORT
        value: 10000

  - type: pserv
    name: webag-db
    env: postgresql
    plan: free
    databaseName: webag_production
    user: webag_user

# Build settings
buildFilter:
  paths:
  - app/**
  - config/**
  - scripts/**
  - static/**
  - templates/**
  - "*.py"
  - requirements.txt
  ignoredPaths:
  - venv/**
  - instance/**
  - "*.log"
  - __pycache__/**